version: 0.1


phases:
  install:
    commands:
      - echo "Install phase"
      - sudo pip install virtualenv
  pre_build:
    commands:
      - echo "pre build phase"
      - virtualenv -p python3.5 tmp/
      - . tmp/bin/activate
      - pip install --upgrade -r config/requirements.txt
  build:
    commands:
      - echo "build phase"
      - cd tmp/lib/python3.5/site-packages/
      - zip -r9 /tmp/rsstotwitter.zip *
      
  post_build:
    commands:
      - echo "post build phase"
artifacts:
  files:
    - target/rsstotwitter.zip
  discard-paths: yes