version: 0.1


phases:
  install:
    commands:
      - echo "Install phase"
      - sudo apt-get clean
      - sudo apt-get -y update && sudo apt-get -y upgrade
      - sudo apt-get -y install python
  pre_build:
    commands:
      - echo "pre build phase"
      - ls -ltr
      - virtualenv /tmp/rssToTwitter
      - source /tmp/rssToTwitter/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo "build phase"
  post_build:
    commands:
      - echo "post build phase"
artifacts:
  files:
    - target/rsstotwitter.zip
  discard-paths: yes