version: 0.1


phases:
  install:
    commands:
      - echo "Install phase"
      - sudo pip install virtualenv
      - /bin/bash
  pre_build:
    commands:
      - echo "pre build phase"
      - pwd
      - ls -la
      - virtualenv /tmp/rssToTwitter
      - source /tmp/rssToTwitter/bin/activate.csh
      - pip install -r config/requirements.txt
  build:
    commands:
      - echo "build phase"
      - ls -la $VIRTUAL_ENV
      - ls -la $VIRTUAL_ENV/lib/
      - cd $VIRTUAL_ENV/lib/python3.5/site-packages/
      - zip -r9 ~/rsstotwitter.zip *

      - cd ~/
      - ls -la
  post_build:
    commands:
      - echo "post build phase"
artifacts:
  files:
    - target/rsstotwitter.zip
  discard-paths: yes