version: 0.1


phases:
  install:
    commands:
      - echo "Install phase"
      - sudo apt-get update -y
      - sudo apt-get install -y zip unzip
      - sudo pip install virtualenv
  pre_build:
    commands:
      - echo "pre build phase"
      - virtualenv -p python3.5 tmp/
      - . tmp/bin/activate
      - pip install --upgrade -r config/requirements.txt
  build:
    commands:
      - echo "build phase"
      - cd tmp/lib/python3.5/site-packages/
      - zip -r9 ../../../../rsstotwitter.zip *
      - cd ../../../../src/
      - zip -rg ../rsstotwitter.zip *
      - cd ../config
      - zip -g ../rsstotwitter.zip twPostsConfig
      - cd ../
  post_build:
    commands:
      - echo "post build phase"
      - cp rsstotwitter.zip /tmp/
artifacts:
  files:
    - target/rsstotwitter.zip
  discard-paths: yes