version: 0.1


phases:
  install:
    commands:
      - echo "Install phase"
      - sudo apt-get update -y
      - sudo apt-get install -y zip unzip
      - sudo pip install virtualenv
  pre_build:
    commands:
      - echo "pre build phase"
  build:
    commands:
      - echo "build phase"
      - config/test_aws.sh
  post_build:
    commands:
      - echo "post build phase"
      - config/build_aws.sh
      - ls -la
artifacts:
  files:
    - /tmp/rsstotwitter.zip
  discard-paths: yes